name: Release

# Trigger the workflow on push to main branch
on:
  push:
    branches:
      - main

# Set permissions for the GITHUB_TOKEN
permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
      # Check out the repository code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      # Install dependencies
      - name: Install dependencies
        run: npm ci
        
      # Run tests to ensure code quality
      - name: Run tests
        run: npm run test:run
        
      # Run linting to ensure code quality  
      - name: Run linting
        run: npm run lint
        
      # Build the project
      - name: Build
        run: npm run build
        
      # Run semantic-release to automatically version and publish
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release